CREATE SCHEMA IF NOT EXISTS budget;

CREATE TABLE IF NOT EXISTS budget.budget_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(500),
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_budget_plans_tenant ON budget.budget_plans(tenant_id);

CREATE TABLE IF NOT EXISTS budget.budget_plan_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_plan_id BIGINT NOT NULL REFERENCES budget.budget_plans(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(160) NOT NULL,
    budget_amount NUMERIC(18,2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_budget_plan_lines_plan ON budget.budget_plan_lines(budget_plan_id);
CREATE INDEX IF NOT EXISTS idx_budget_plan_lines_category ON budget.budget_plan_lines(category_id);

CREATE TABLE IF NOT EXISTS budget.budget_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    budget_plan_id BIGINT NOT NULL REFERENCES budget.budget_plans(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    total_budget NUMERIC(18,2) NOT NULL,
    total_spent NUMERIC(18,2) NOT NULL,
    variance NUMERIC(18,2) NOT NULL,
    compliant BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (budget_plan_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_budget_snapshots_tenant_plan ON budget.budget_snapshots(tenant_id, budget_plan_id);
CREATE INDEX IF NOT EXISTS idx_budget_snapshots_period ON budget.budget_snapshots(period_start, period_end);

CREATE TABLE IF NOT EXISTS budget.budget_snapshot_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_snapshot_id BIGINT NOT NULL REFERENCES budget.budget_snapshots(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(160) NOT NULL,
    budget_amount NUMERIC(18,2) NOT NULL,
    spent_amount NUMERIC(18,2) NOT NULL,
    variance NUMERIC(18,2) NOT NULL,
    transaction_count BIGINT NOT NULL,
    compliant BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_budget_snapshot_lines_snapshot ON budget.budget_snapshot_lines(budget_snapshot_id);
