services:
  banking:
    build:
      context: .
      dockerfile: banking/Dockerfile
    env_file:
      - ./banking/.env
    ports:
      - "8081:8081"
    networks:
      - finance-net

  investments:
    build:
      context: .
      dockerfile: investments/Dockerfile
    env_file:
      - ./investments/.env
    ports:
      - "8082:8082"
    networks:
      - finance-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_KEYCLOAK_BASE_URL: ${VITE_KEYCLOAK_BASE_URL}
        VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM}
        VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID}
    depends_on:
      - banking
      - investments
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    networks:
      - finance-net

networks:
  finance-net:
    external: true