
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: ${KEYCLOAK_DOMAIN:-auth.local}
      KC_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    networks:
      - finance-net
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
    driver: local

networks:
  finance-net:
    external: true
